//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoProject1
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using Eco.Services;
    using Eco.ObjectRepresentation;
    using Eco.ObjectImplementation;
    using Eco.Subscription;
    using Eco.UmlRt;
    using Eco.UmlCodeAttributes;

    [UmlElement("Package", Id = "eb18d545-8d55-4a15-b9ba-13e814742fec")]
    [UmlTaggedValue("Eco.ModeledName", "EcoProject1Package")]
    [UmlMetaAttribute("ownedElement", typeof(EcoProject1.Class1))]
    [UmlMetaAttribute("ownedElement", typeof(EcoProject1.Class2))]
    public abstract partial class EcoProject1Package
    {

        [UmlElement("Association", Id = "f285e989-16c8-4fc7-b9bc-9c6ff5ca5e0d")]
        public class Class1Class1Class2Class2
        {
        }
    }
}
